<?php
/**
 * Created by PhpStorm.
 * User: jofo
 * Date: 2017/9/4
 * Time: 下午 2:27
 */

namespace Ksd\Mediation\Parameter\Cart;


use Ksd\Mediation\Config\ProjectConfig;
use Ksd\Mediation\Parameter\BaseParameter;

class ProductParameter extends BaseParameter
{
    private $magento;
    private $cityPass;

    public function codeigniterRequest($input, $parameters = null)
    {
        $this->request($parameters);
        parent::codeigniterRequest($input);
    }

    /**
     * laravel request 參數處理
     * @param $request
     */
    public function laravelRequest($request)
    {
        $this->request($request->all());
        parent::laravelRequest($request); // TODO: Change the autogenerated stub
    }

    /**
     * 參數處理
     * @param $parameters
     */
    private function request($parameters)
    {
        $this->magento = [];
        $this->cityPass = [];
        if (!empty($parameters)) {
                if ($parameters['source'] === ProjectConfig::MAGENTO) {
                    array_push($this->magento, $parameters);
                } else if ($parameters['source'] === ProjectConfig::CITY_PASS || $parameters['source'] === ProjectConfig::CITY_PASS_PHYSICAL) {
                    array_push($this->cityPass, $parameters);
                }

        }
    }

    /**
     * 取得 magento來源 購物車商品資訊
     * @return mixed
     */
    public function magento()
    {
        return $this->magento;
    }

    /**
     * 取得 city pass來源 購物車商品資訊
     * @return mixed
     */
    public function cityPass()
    {
        return $this->cityPass;
    }
}