<?php
/**
 * Created by PhpStorm.
 * User: jofo
 * Date: 2017/9/4
 * Time: 下午 2:27
 */

namespace Ksd\Mediation\Parameter\Cart;


use Ksd\Mediation\Config\ProjectConfig;
use Ksd\Mediation\Parameter\BaseParameter;

class ProductParameter extends BaseParameter
{
    private $magento;
    private $tpass;

    public function codeigniterRequest($input, $parameters = null)
    {
        $this->request($parameters);
        parent::codeigniterRequest($input);
    }

    public function laravelRequest($request)
    {
        $this->request($request->all());
        parent::laravelRequest($request); // TODO: Change the autogenerated stub
    }

    private function request($parameters)
    {
        $this->magento = [];
        $this->tpass = [];
        if (!empty($parameters)) {
            foreach ($parameters as $parameter) {
                if ($parameter['source'] === ProjectConfig::MAGENTO) {
                    array_push($this->magento, $parameter);
                } else if ($parameter['source'] === ProjectConfig::TPASS) {
                    array_push($this->tpass, $parameter);
                }
            }
        }
    }

    public function magento()
    {
        return $this->magento;
    }

    public function tpass()
    {
        return $this->tpass;
    }
}